// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzGsjo42qELbWX0S5T9FfweVdS6KJKXDI',
    appId: '1:648240819521:web:9710fae3e6a1ae4130c5c0',
    messagingSenderId: '648240819521',
    projectId: 'chat-app-f5826',
    authDomain: 'chat-app-f5826.firebaseapp.com',
    storageBucket: 'chat-app-f5826.appspot.com',
    measurementId: 'G-4WXWHWNBF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpUgHM9Va6ihQd9FOJfVTyTUwwcxC25kU',
    appId: '1:648240819521:android:d25ca680638dbfb930c5c0',
    messagingSenderId: '648240819521',
    projectId: 'chat-app-f5826',
    storageBucket: 'chat-app-f5826.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOIV996Rgwv0zmzhO4j1ssaOy7F1kovI',
    appId: '1:648240819521:ios:c16d88c7e874ed4630c5c0',
    messagingSenderId: '648240819521',
    projectId: 'chat-app-f5826',
    storageBucket: 'chat-app-f5826.appspot.com',
    iosClientId: '648240819521-4ql05diiv1hierpji2org09eillipd3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOIV996Rgwv0zmzhO4j1ssaOy7F1kovI',
    appId: '1:648240819521:ios:c16d88c7e874ed4630c5c0',
    messagingSenderId: '648240819521',
    projectId: 'chat-app-f5826',
    storageBucket: 'chat-app-f5826.appspot.com',
    iosClientId: '648240819521-4ql05diiv1hierpji2org09eillipd3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
